import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';

const robot = Roboto({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={robot.className} lang='en'>
      <body>
        <div className='flex flex-col'>
          <main className='flex-grow'>{children}</main>
        </div>
      </body>
    </html>
  );
}
